name: "Validate Sentry Options Schema"
description: "Installs sentry-options-cli and runs validate-schema-changes"

runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain
      shell: bash
      run: rustup toolchain install stable --profile minimal --component clippy --component rustfmt --no-self-update

    - name: Cache Cargo
      uses: swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

    - name: Install sentry-options-cli
      shell: bash
      run: cargo install sentry-options-cli --version "0.0.4" --locked

    - name: Validate schema changes
      shell: bash
      run: |
        set -euo pipefail
        sentry-options-cli validate-schema-changes --base-sha ${{github.base_ref}} --head-sha ${{github.head_ref}}
