minVersion: 1.2.0
changelog: CHANGELOG.md
changelogPolicy: auto
preReleaseCommand: bash scripts/bump-version.sh
github:
  owner: getsentry
  repo: sentry-options
artifactProvider:
  name: github
requireNames:
  - /^sentry_options-.*\.tar\.gz$/                  # sdist
  - /^sentry_options-.*manylinux.*x86_64\.whl$/     # Linux x86_64 wheel
  - /^sentry_options-.*manylinux.*aarch64\.whl$/    # Linux ARM wheel
  - /^sentry_options-.*macosx.*x86_64\.whl$/        # macOS Intel wheel
  - /^sentry_options-.*macosx.*arm64\.whl$/         # macOS ARM wheel
  - /^sentry-options-cli$/                          # Rust CLI binary
targets:
  - name: github
  - name: crates
  - name: pypi
    includeNames: /^sentry_options.*$/
  - name: sentry-pypi
    includeNames: /^sentry_options.*\.whl$/
    internalPypiRepo: getsentry/pypi
