minVersion: 1.2.0
changelog: CHANGELOG.md
changelogPolicy: auto
preReleaseCommand: bash scripts/bump-version.sh
github:
  owner: getsentry
  repo: sentry-options
artifactProvider:
  name: github
requireNames:
  - /^sentry_options-.*\.tar\.gz$/           # sdist
  - /^sentry_options-.*manylinux.*\.whl$/    # Linux wheel
  - /^sentry_options-.*macosx.*x86_64\.whl$/ # macOS Intel wheel
  - /^sentry_options-.*macosx.*arm64\.whl$/  # macOS ARM wheel
targets:
  - name: github
  - name: crates
  - name: pypi
    includeNames: /^sentry_options.*$/
  - name: sentry-pypi
    includeNames: /^sentry_options.*$/
    internalPypiRepo: getsentry/pypi
