#!/usr/bin/env python
"""
Snapshot all 'active' options from a fully-initialized getsentry instance.

After the app warms up, options can hold non-default values from three sources:

  DB          — operator-set values written to `sentry_option` /
                `sentry_controloption` via the admin UI, sentry CLI, or
                automation.  These are the values that matter most: static
                analysis cannot see them, but they prove an option is live.

  disk        — values in settings.SENTRY_OPTIONS, set by getsentry's Python
                settings files (e.g. conf/settings/defaults.py, cellsilo.py).
                These should already be NEVER_DELETE in the static inventory
                (the string pass finds them), but the list here lets you verify
                that assumption.

  default     — values in settings.SENTRY_DEFAULT_OPTIONS, set
                programmatically at startup.

Cross-referencing `has_db_value` against SAFE_CANDIDATEs in the static
inventory is the primary purpose of this script.  Any SAFE_CANDIDATE that
appears here warrants a closer look before deletion.

Usage (run from anywhere):
    python scripts/migration/enumerate_active_options.py \\
        [--getsentry ~/dev/getsentry] \\
        [--db-name sentry] \\
        > scripts/migration/active_options.json

The script is read-only: it issues only SELECT queries and makes no changes.
Requires a running local Postgres (devserver does not need to be up).
Uses skip_service_validation=True so Redis/Kafka are not required.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import UTC, datetime

parser = argparse.ArgumentParser(description='Snapshot active getsentry options')
parser.add_argument(
    '--getsentry',
    default=os.path.expanduser('~/dev/getsentry'),
    help='Path to the getsentry repo (default: ~/dev/getsentry)',
)
parser.add_argument(
    '--db-name', default=None,
    help='Override the Django default DB name '
         '(e.g. --db-name sentry if the local DB is named sentry)',
)
args = parser.parse_args()

# cd to getsentry so relative imports and SENTRY_CONF work correctly.
getsentry_root = os.path.realpath(args.getsentry)
if not os.path.isdir(getsentry_root):
    print(f'ERROR: getsentry path not found: {getsentry_root}', file=sys.stderr)
    sys.exit(1)
os.chdir(getsentry_root)

# Add sentry to sys.path if needed (mirrors how bin/mock-customer is invoked
# after sourcing the sentry .envrc which activates the venv).
_venv = os.path.join(os.path.dirname(getsentry_root), 'sentry', '.venv', 'lib')
if os.path.isdir(_venv):
    import glob as _glob
    for _sp in _glob.glob(os.path.join(_venv, 'python*', 'site-packages')):
        if _sp not in sys.path:
            sys.path.insert(0, _sp)

os.environ.setdefault('SENTRY_CONF', 'getsentry/settings.py')

from sentry.runner import configure

# skip_service_validation: we only need Postgres; no Redis/Kafka required.
configure(skip_service_validation=True)

if args.db_name:
    from django.conf import settings as _s
    _s.DATABASES['default']['NAME'] = args.db_name


def _query_db_keys() -> set[str]:
    """Return all option keys that have an explicit value in the database."""
    keys: set[str] = set()
    try:
        from sentry.models.options.option import ControlOption, Option
        keys |= set(Option.objects.values_list('key', flat=True))
        keys |= set(ControlOption.objects.values_list('key', flat=True))
    except Exception as exc:
        print(f'WARNING: could not query option tables: {exc}', file=sys.stderr)
    return keys


def main() -> None:
    from django.conf import settings
    from sentry import options as options_module

    all_registered = sorted(key.name for key in options_module.all())
    registered_set = set(all_registered)

    db_keys      = _query_db_keys()
    disk_keys    = set(getattr(settings, 'SENTRY_OPTIONS', {}).keys())
    default_keys = set(getattr(settings, 'SENTRY_DEFAULT_OPTIONS', {}).keys())

    has_db      = sorted(db_keys & registered_set)
    has_disk    = sorted(disk_keys & registered_set)
    has_default = sorted(default_keys & registered_set)
    has_any     = sorted((db_keys | disk_keys | default_keys) & registered_set)
    unknown_db  = sorted(db_keys - registered_set)

    output = {
        '_note': (
            'Generated by enumerate_active_options.py. '
            'See scripts/migration/README.md for cross-referencing instructions.'
        ),
        '_generated_at': datetime.now(UTC).isoformat(),
        '_sentry_options_count': len(all_registered),
        'all_registered': all_registered,
        'has_db_value': has_db,
        'has_disk_value': has_disk,
        'has_default_override': has_default,
        'has_any_value': has_any,
        'unknown_db_keys': unknown_db,
    }

    json.dump(output, sys.stdout, indent=2)
    sys.stdout.write('\n')

    print(file=sys.stderr)
    print(f'registered options:    {len(all_registered)}', file=sys.stderr)
    print(f'db values:             {len(has_db)}', file=sys.stderr)
    print(f'disk values:           {len(has_disk)}', file=sys.stderr)
    print(f'default overrides:     {len(has_default)}', file=sys.stderr)
    print(f'any non-default:       {len(has_any)}', file=sys.stderr)
    if unknown_db:
        print(file=sys.stderr)
        print(
            f'unknown db keys ({len(unknown_db)}) — in DB but not found by registration scanner:',
            file=sys.stderr,
        )
        for k in unknown_db:
            print(f'  {k}', file=sys.stderr)


if __name__ == '__main__':
    main()
