# AUTO-GENERATED by sentry-options-gen-stubs — do not edit manually.
# Run `sentry-options-gen-stubs` to regenerate.
from __future__ import annotations

from typing import Literal, NotRequired, TypedDict, overload

from sentry_options._core import (
    NotInitializedError,
    NamespaceOptions,
    OptionsError,
    OptionValue,
    SchemaError,
    UnknownNamespaceError,
    UnknownOptionError,
    init,
)

_NamespaceOptions_sentry_options_testing_0_Dict = TypedDict('_NamespaceOptions_sentry_options_testing_0_Dict', {
    'host': str,
    'port': int,
})

_NamespaceOptions_sentry_options_testing_1_Item = TypedDict('_NamespaceOptions_sentry_options_testing_1_Item', {
    'url': str,
    'weight': int,
})

@overload
def options(namespace: Literal["sentry-options-testing"]) -> NamespaceOptions_sentry_options_testing: ...
@overload
def options(namespace: str) -> NamespaceOptions: ...

class NamespaceOptions_sentry_options_testing(NamespaceOptions):
    @overload
    def get(self, key: Literal["example-option"]) -> str: ...
    @overload
    def get(self, key: Literal["float-option"]) -> float: ...
    @overload
    def get(self, key: Literal["int-option"]) -> int: ...
    @overload
    def get(self, key: Literal["bool-option"]) -> bool: ...
    @overload
    def get(self, key: Literal["string-option"]) -> str: ...
    @overload
    def get(self, key: Literal["demo-option"]) -> str: ...
    @overload
    def get(self, key: Literal["object-option"]) -> _NamespaceOptions_sentry_options_testing_0_Dict: ...
    @overload
    def get(self, key: Literal["endpoints-option"]) -> list[_NamespaceOptions_sentry_options_testing_1_Item]: ...
    @overload
    def get(self, key: Literal["array-option"]) -> list[int]: ...
    @overload
    def get(self, key: str) -> OptionValue: ...
