from __future__ import annotations

from typing import Union

_Primitive = Union[str, int, float, bool]
_Object = dict[str, _Primitive]
OptionValue = Union[_Primitive, _Object, list[Union[_Primitive, _Object]]]

def init() -> None: ...
def options(namespace: str) -> NamespaceOptions: ...

class NamespaceOptions:
    def get(self, key: str) -> OptionValue: ...
    def isset(self, key: str) -> bool: ...
    def __repr__(self) -> str: ...

class OptionsError(Exception): ...
class SchemaError(OptionsError): ...
class UnknownNamespaceError(OptionsError): ...
class UnknownOptionError(OptionsError): ...
class InitializationError(OptionsError): ...

def _set_override(namespace: str, key: str, value: OptionValue) -> OptionValue | None: ...
def _clear_override(namespace: str, key: str) -> None: ...
def _validate_option(namespace: str, key: str, value: OptionValue) -> None: ...
