from __future__ import annotations

from typing import Any

def init() -> None: ...
def options(namespace: str) -> NamespaceOptions: ...

class NamespaceOptions:
    def get(self, key: str) -> Any: ...
    def isset(self, key: str) -> bool: ...
    def __repr__(self) -> str: ...

class OptionsError(Exception): ...
class SchemaError(OptionsError): ...
class UnknownNamespaceError(OptionsError): ...
class UnknownOptionError(OptionsError): ...
class InitializationError(OptionsError): ...

def _set_override(namespace: str, key: str, value: Any) -> Any: ...
def _clear_override(namespace: str, key: str) -> None: ...
def _validate_option(namespace: str, key: str, value: Any) -> None: ...
