"""
Generate typed mypy stubs for sentry_options based on local schemas.

Reads <schemas-dir>/<namespace>/schema.json and produces
stubs/sentry_options/__init__.pyi with per-namespace NamespaceOptions
subclasses and overloaded options() signatures, so opts.get("key")
returns the correct type without needing cast().

Everything else (init, exceptions, NamespaceOptions base, etc.) is
re-exported from sentry_options._core via wildcard import.

CLI usage:
    sentry-options-gen-stubs
    sentry-options-gen-stubs --schemas-dir path/to/schemas \
        --output stubs/sentry_options/__init__.pyi
    sentry-options-gen-stubs --check
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SCHEMA_TYPE_MAP = {
    'string': 'str',
    'integer': 'int',
    'number': 'float',
    'boolean': 'bool',
    'array': 'list[object]',
    'object': 'dict[str, object]',
}


def namespace_to_class(namespace: str) -> str:
    return 'NamespaceOptions_' + re.sub(r'[^a-zA-Z0-9]', '_', namespace)


def generate(schemas_dir: Path) -> str:
    schema_dirs = sorted(p for p in schemas_dir.iterdir() if p.is_dir())
    if not schema_dirs:
        print(f"No schemas found under {schemas_dir}", file=sys.stderr)
        sys.exit(1)

    namespaces: list[tuple[str, str, dict[str, str]]] = []
    for schema_dir in schema_dirs:
        schema_file = schema_dir / 'schema.json'
        if not schema_file.exists():
            continue
        schema = json.loads(schema_file.read_text())
        namespace = schema_dir.name
        class_name = namespace_to_class(namespace)
        key_types = {
            key: SCHEMA_TYPE_MAP.get(prop.get('type', ''), 'object')
            for key, prop in schema.get('properties', {}).items()
        }
        namespaces.append((namespace, class_name, key_types))

    lines = [
        '# AUTO-GENERATED by sentry-options-gen-stubs — do not edit manually.',
        '# Run `sentry-options-gen-stubs` to regenerate.',
        'from __future__ import annotations',
        '',
        'from typing import Literal, overload',
        '',
        'from sentry_options._core import *  # noqa: F401, F403',
        'from sentry_options._core import NamespaceOptions, OptionValue',
        '',
    ]

    for namespace, class_name, _ in namespaces:
        lines.append(
            f'@overload\n'
            f'def options(namespace: Literal["{namespace}"])'
            f' -> {class_name}: ...',
        )
    lines.append(
        '@overload\ndef options(namespace: str) -> NamespaceOptions: ...',
    )
    lines.append('')

    for namespace, class_name, key_types in namespaces:
        lines.append(f"class {class_name}(NamespaceOptions):")
        for key, py_type in key_types.items():
            lines.append(
                f'    @overload\n'
                f'    def get(self, key: Literal["{key}"]) -> {py_type}: ...',
            )
        lines.append(
            '    @overload\n    def get(self, key: str) -> OptionValue: ...',
        )
        lines.append('')

    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Generate sentry_options mypy stubs from schemas.',
    )
    parser.add_argument(
        '--schemas-dir',
        type=Path,
        default=Path('sentry-options/schemas'),
        help=(
            'Directory containing <namespace>/schema.json files'
            ' (default: sentry-options/schemas)'
        ),
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=Path('stubs/sentry_options/__init__.pyi'),
        help='Output path (default: stubs/sentry_options/__init__.pyi)',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help=(
            'Exit with code 1 if the output would change'
            ' (for CI/pre-commit).'
        ),
    )
    args = parser.parse_args()

    content = generate(args.schemas_dir)

    if args.check:
        if not args.output.exists() or args.output.read_text() != content:
            print(
                f"error: {args.output} is out of date."
                ' Run `sentry-options-gen-stubs`.',
                file=sys.stderr,
            )
            sys.exit(1)
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    print(f"Written to {args.output}")


if __name__ == '__main__':
    main()
