"""
Generate typed mypy stubs for sentry_options based on local schemas.

Reads <schemas-dir>/<namespace>/schema.json and produces
stubs/sentry_options/__init__.pyi with per-namespace NamespaceOptions
subclasses and overloaded options() signatures, so opts.get("key")
returns the correct type without needing cast().

Everything else (init, exceptions, NamespaceOptions base, etc.) is
re-exported from sentry_options._core via explicit imports.

CLI usage:
    sentry-options-gen-stubs
    sentry-options-gen-stubs --schemas-dir path/to/schemas \
        --output sentry-options/sentry_options/__init__.pyi
    sentry-options-gen-stubs --check
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

_SCHEMA_TO_PYTHON = {
    'string': 'str',
    'integer': 'int',
    'number': 'float',
    'boolean': 'bool',
}


def _ident(s: str) -> str:
    return re.sub(r'[^a-zA-Z0-9]', '_', s)


def namespace_to_class(namespace: str) -> str:
    return 'NamespaceOptions_' + _ident(namespace)


def _resolve_type(
    prop: dict,
    class_name: str,
    key: str,
    typed_dicts: dict[str, list[tuple[str, str]]],
    counter: list[int],
    suffix: str = 'Dict',
) -> str:
    """Resolve a value-type schema to a Python type string, recursively.

    Scalars map to str/int/float/bool. Arrays resolve to list[T]. Maps
    (objects with `additionalProperties` and no `properties`) resolve to
    dict[str, V]. Fixed-shape objects (with `properties`) generate a TypedDict
    collected into typed_dicts. Value types nest arbitrarily, so every
    container recurses into its element/value schema.

    TypedDicts use index-based names to avoid collisions and the functional
    form to preserve original key names (e.g. hyphens). `suffix` names the
    generated TypedDict: array items use `_Item`, every other object `_Dict`.
    """
    t = prop.get('type', '')
    if t in _SCHEMA_TO_PYTHON:
        return _SCHEMA_TO_PYTHON[t]
    if t == 'array':
        items = prop.get('items')
        if not items:
            raise ValueError(f'{key!r}: array has no items')
        inner = _resolve_type(items, class_name, key, typed_dicts, counter, 'Item')
        return f'list[{inner}]'
    if t == 'object':
        obj_props = prop.get('properties')
        if obj_props:
            td = f'_{class_name}_{counter[0]}_{suffix}'
            counter[0] += 1
            typed_dicts[td] = [
                (k, _field_type(v, class_name, f'{key}.{k}', typed_dicts, counter))
                for k, v in obj_props.items()
            ]
            return td
        value_type = prop.get('additionalProperties')
        if isinstance(value_type, dict):
            inner = _resolve_type(value_type, class_name, key, typed_dicts, counter)
            return f'dict[str, {inner}]'
        raise ValueError(
            f'{key!r}: object has neither properties nor additionalProperties',
        )
    raise ValueError(f'{key!r}: unknown type {t!r}')


def _field_type(
    prop: dict,
    class_name: str,
    key: str,
    typed_dicts: dict[str, list[tuple[str, str]]],
    counter: list[int],
) -> str:
    """Resolve a TypedDict field type, wrapping optional fields in NotRequired."""
    inner = _resolve_type(prop, class_name, key, typed_dicts, counter)
    if prop.get('optional'):
        return f'NotRequired[{inner}]'
    return inner


def generate(schemas_dir: Path) -> str:
    if not schemas_dir.is_dir():
        print(
            f"error: schemas directory not found: {schemas_dir}",
            file=sys.stderr,
        )
        sys.exit(1)
    schema_dirs = sorted(p for p in schemas_dir.iterdir() if p.is_dir())

    raw_namespaces: list[tuple[str, str, dict]] = []
    for schema_dir in schema_dirs:
        schema_file = schema_dir / 'schema.json'
        if not schema_file.exists():
            continue
        schema = json.loads(schema_file.read_text())
        namespace = schema_dir.name
        class_name = namespace_to_class(namespace)
        raw_namespaces.append(
            (namespace, class_name, schema.get('properties', {})),
        )

    if not raw_namespaces:
        print(f"No schemas found under {schemas_dir}", file=sys.stderr)
        sys.exit(1)

    typed_dicts: dict[str, list[tuple[str, str]]] = {}
    namespaces: list[tuple[str, str, dict[str, str]]] = []
    for namespace, class_name, props in raw_namespaces:
        try:
            counter = [0]
            key_types = {
                key: _resolve_type(prop, class_name, key, typed_dicts, counter)
                for key, prop in props.items()
                if '$ref' not in prop
            }
        except ValueError as e:
            print(f"error: {namespace}: {e}", file=sys.stderr)
            sys.exit(1)
        namespaces.append((namespace, class_name, key_types))

    lines = [
        '# AUTO-GENERATED by sentry-options-gen-stubs — do not edit manually.',
        '# Run `sentry-options-gen-stubs` to regenerate.',
        'from __future__ import annotations',
        '',
        'from typing import Literal, NotRequired, TypedDict, overload',
        '',
        'from sentry_options._core import ('
        '\n    FeatureChecker,'
        '\n    FeatureContext,'
        '\n    NotInitializedError,'
        '\n    NamespaceOptions,'
        '\n    OptionsError,'
        '\n    OptionValue,'
        '\n    SchemaError,'
        '\n    UnknownNamespaceError,'
        '\n    UnknownOptionError,'
        '\n    features,'
        '\n    init,'
        '\n)',
        '',
        '__all__ = [',
        '    "init",',
        '    "options",',
        '    "features",',
        '    "FeatureChecker",',
        '    "FeatureContext",',
        '    "NotInitializedError",',
        '    "NamespaceOptions",',
        '    "OptionsError",',
        '    "OptionValue",',
        '    "SchemaError",',
        '    "UnknownNamespaceError",',
        '    "UnknownOptionError",',
        ']',
        '',
    ]

    for td_name, fields in typed_dicts.items():
        lines.append(f"{td_name} = TypedDict('{td_name}', {{")
        for field_name, field_type in fields:
            lines.append(f"    '{field_name}': {field_type},")
        lines.append('})')
        lines.append('')

    for namespace, class_name, _ in namespaces:
        lines.append(
            f'@overload\n'
            f'def options(namespace: Literal["{namespace}"])'
            f' -> {class_name}: ...',
        )
    lines.append(
        '@overload\ndef options(namespace: str) -> NamespaceOptions: ...',
    )
    lines.append('')

    for namespace, class_name, key_types in namespaces:
        lines.append(f'class {class_name}(NamespaceOptions):')
        for key, py_type in key_types.items():
            lines.append(
                f'    @overload\n'
                f'    def get(self, key: Literal["{key}"]) -> {py_type}: ...',
            )
        if key_types:
            lines.append(
                '    @overload\n    def get(self, key: str) -> OptionValue: ...',
            )
        else:
            lines.append('    def get(self, key: str) -> OptionValue: ...')
        lines.append('')

    while lines and lines[-1] == '':
        lines.pop()
    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Generate sentry_options mypy stubs from schemas.',
    )
    parser.add_argument(
        '--schemas-dir',
        type=Path,
        default=Path('sentry-options/schemas'),
        help=(
            'Directory containing <namespace>/schema.json files'
            ' (default: sentry-options/schemas)'
        ),
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=Path('sentry-options/sentry_options/__init__.pyi'),
        help='Output path (default: sentry-options/sentry_options/__init__.pyi)',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help=(
            'Exit with code 1 if the output would change'
            ' (for CI/pre-commit).'
        ),
    )
    args = parser.parse_args()

    content = generate(args.schemas_dir)

    if args.check:
        if not args.output.exists() or args.output.read_text() != content:
            print(
                f"error: {args.output} is out of date."
                ' Run `sentry-options-gen-stubs`.',
                file=sys.stderr,
            )
            sys.exit(1)
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    print(f"Written to {args.output}")


if __name__ == '__main__':
    main()
